# Data Analysis Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

# append two lists together
print(f'Sum of {l_1} + {1_2} using python operators in one line: {l_1 + l_2}')
# error: print(f'Difference of {l_1} - {1_2} using python operators in one line: {l_1 - l_2}')

Sum of [1, 2, 3] + 12 using python operators in one line: [1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [2]:
#output: [3,8,6]
l_1 = [2,3,4]
l_2 = [1,5,2]
def listSum(list1,list2):
    list3 = []
    for i in range(len(list1)):
        list3.append(list1[i]+list2[i])
    return list3
print(listSum(l_1,l_2))

# print(l_1[0] + l_2[0], l_1[1] + l_2[1], l_1[2] + l_2[2])
    

[3, 8, 6]


#### Importing

In [4]:
# always import as np, standard across all of data science/analysis
# !pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [6]:
arr_1 = [0,1,2,3]

new_arr = np.array(arr_1)
print(arr_1)
print(new_arr)
# np.array does not return with commas
# to make into NDArray
print(arr_1)
type(new_arr)

[0, 1, 2, 3]
[0 1 2 3]
[0, 1, 2, 3]


numpy.ndarray

###### - np.zeros()

In [9]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [13]:
arr_ones = np.ones((3,3), int) 
arr_ones_flt = np.ones((3,3)) 
arr_ones
# arr_ones_flt
# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [15]:
arr_range = np.arange(1,11)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###### - Making Lists into NDArrays

In [17]:
some_list = [99,14,7]
numpy_array = np.array(some_list)
numpy_array

np_arr_2 = np.array([99,14,7])
np_arr_2

# can be used either way

array([99, 14,  7])

#### Performing Calculations on NDArrays

###### - Summation

In [21]:
np_list = np.array([5,10,15,20,25,30])
np_list_2 = np.array([10,20,30,40,50,60])

result_sum = np_list + np_list_2
result_sum

array([15, 30, 45, 60, 75, 90])

###### - Difference

In [22]:
result_diff = np_list - np_list_2
result_diff

array([ -5, -10, -15, -20, -25, -30])

###### - Multiplication

In [23]:
result_prod = np_list * np_list_2
result_prod

array([  50,  200,  450,  800, 1250, 1800])

###### - Division

In [24]:
result_div = np_list / np_list_2
result_div

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

#### Modulo

In [27]:
result_mod = np_list % np_list_2
result_mod

array([ 5, 10, 15, 20, 25, 30])

#### Floor Division

In [30]:
result_floor = np_list // np_list_2
result_floor

array([0, 0, 0, 0, 0, 0])

#### Numpy Subsetting

In [39]:
# result3 <= 800
print(result_prod)
print(result_prod <= 800)
# comparing a list to <=800

test_nums = np.array([1,2,3,4,5])
new_nums = test_nums[test_nums < 5]
print(new_nums)
# loop [test_nums < 5] with True or False statement 

test_ndStrings = np.array(['Bob','Mark','Bob','Barb'])
print(test_ndStrings[test_ndStrings == 'Bob'])
# show which names start with the Bob



# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)
# conditional check, that returns the elements that meet the given condition
for name in test_ndStrings:
    if name[0] == 'B':
        print(name)
        
np.array([name for name in test_ndStrings if name[0] == 'B'])

[  50  200  450  800 1250 1800]
[ True  True  True  True False False]
[1 2 3 4]
['Bob' 'Bob']
Bob
Bob
Barb


array(['Bob', 'Bob', 'Barb'], dtype='<U4')

#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [43]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
# a list inside of list
M = [aList, bList, cList]
print(M)
print(M[2])
print(M[2][0])


# second step: place Matrix inside NDArray
ND_M = np.array(M)
ND_M

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[6, 7, 8]
6


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [44]:
#in order to grab the 0th index from the 3rd row
ND_M[2,0]

6

#### Assigning Values in NDArrays

In [45]:
#Changing/assigning value
ND_M[2,0] = 10
ND_M

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10,  7,  8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [46]:
# using the .dtype method
nd_type = ND_M.dtype
nd_type

dtype('int64')

#### Altering NDArray Type

In [49]:
print(nd_type)

#creating a new array and chaning data type
changed = ND_M.astype(np.float32)
#when using .astype creates new copy

#dtype of new matrix if float32
changed.dtype
changed

int64


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [10.,  7.,  8.]], dtype=float32)

In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [51]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

# print(type(result_changed.shape))

changed.shape
ND_M.shape

# (3,3) three rows by three columns

(3, 3)

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [58]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

print(changed)
# (9,1) == 9 rows , 1 column
new = changed.reshape(9,1)
new

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [10.  7.  8.]]


array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [10.],
       [ 7.],
       [ 8.]], dtype=float32)

In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [67]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
new = np.array(range(0,16)).reshape(4,4)
print(new)

#using np.arange
other_M = np.arange(16).reshape(4,4)
print("\n",other_M)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### Complex Indexing & Assinging

In [90]:
M2 = np.zeros((6,6), int)
print(M2)

# Set every first element in each row to 1
M2[0,0] = 1
print("\n",M2)

M2[0:6,0] = 1
print("\n",M2)

# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
M2[3:5,:] = 5
print("\n",M2)


# reset the matrix back to 0
M2 = M2 * 0
print("\n",M2)

# Set the second and third columns to a number == 2
M2[:,2:4] = 2
print("\n",M2)

# Creating a vector in numpy
x = np.arange(6)
print(x)

# Reset the Matrix to 0
M2 = M2 * 0
print("\n",M2)

# Set the first row of data to that range of vector numbers we just created
M2[0,:] = x
print("\n",M2)

M2[:,0] = x
print("\n",M2)

np.append(M2, [x], axis=0)

#################
# M[rows,columns]
#################

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]

 [[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [1 0 0 0 0 0]]

 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]]
[0 1 2 3 4 5]

 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[0 1 2 3 4 5]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[0 1 2 3 4 5]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]


array([[0, 1, 2, 3, 4, 5],
       [1, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4, 5]])

#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [91]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
# Matrix of rows and colomuns M[:,:]
print(M2)
v = M2[:,:]
v
# Reset the Matrix to 0
v = v * 0
print(v)
print(M2)

# changing bottom row to be full of 2's
v[5,:] = 2
print(v)

new_matrix = M2 * v
print(new_matrix)

[[0 1 2 3 4 5]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 1 2 3 4 5]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [2 2 2 2 2 2]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [10  0  0  0  0  0]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [95]:
new_arr = np.array([400,500,600,700])
print(new_arr)
print(np.where(new_arr < 600))

# Transform Data based on boolean mask == True
new_arr[np.where(new_arr < 700)] == 400

# subsetting syntax
new_arr[new_arr < 600] == 400

[400 500 600 700]
(array([0, 1]),)


array([ True, False])

#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [96]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))
# 1e6, 1 million

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.29480034085069784
Here is a random number between 0 and 1 Million: 300473.0676170724
Here are 5 random numbers between 0 and 10: [0.78337381 4.13290022 6.81090713 1.40255552 0.94976909]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[4.29371429 6.34056321 4.24692146]
 [1.65349637 9.47126405 1.99466078]
 [3.16227845 2.0504489  8.17475106]]


## Working With CSV's

#### Imports

In [97]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [98]:
# Creating Function to open and read CSV data
# Comma Separated Values

def open_csv(filepath, d = ','):
#     instantiate an empty dataset
    data = []
    with open(filepath, encoding = 'utf-8') as myData:
        #use csv reader from docs to parse through csv
        info = csv.reader(myData, delimiter = d)
        
#         Loop over information and append to data list
        for row in info:
            data.append(row)
    return data

# use our function to open marathon 2017
csv_data = open_csv('../files/boston_marathon2017_edited.csv')
csv_data[1:5]


[['12/30/1899 12:30:28 AM',
  '12/30/1899 12:45:44 AM',
  '12/30/1899 1:01:15 AM',
  '12/30/1899 1:16:59 AM',
  '12/30/1899 1:33:01 AM',
  '12/30/1899 1:48:19 AM',
  '12/30/1899 2:02:53 AM',
  '12/30/1899 12:15:25 AM',
  '24',
  '11',
  '7777',
  'KEN',
  '7777',
  '',
  'Keringet',
  'KEN',
  '1',
  '1',
  '12/30/1899 1:04:35 AM',
  'M',
  'Kirui, Geoffrey',
  '1',
  '12/30/1899 2:09:37 AM',
  '1',
  '12/30/1899 12:04:57 AM',
  ''],
 ['12/30/1899 12:30:27 AM',
  '12/30/1899 12:45:44 AM',
  '12/30/1899 1:01:15 AM',
  '12/30/1899 1:16:59 AM',
  '12/30/1899 1:33:01 AM',
  '12/30/1899 1:48:19 AM',
  '12/30/1899 2:03:14 AM',
  '12/30/1899 12:15:24 AM',
  '30',
  '17',
  '7798',
  'USA',
  '7798',
  '',
  'Portland',
  'USA',
  '2',
  '2',
  '12/30/1899 1:04:35 AM',
  'M',
  'Rupp, Galen',
  '1',
  '12/30/1899 2:09:58 AM',
  '2',
  '12/30/1899 12:04:58 AM',
  'OR'],
 ['12/30/1899 12:30:29 AM',
  '12/30/1899 12:45:44 AM',
  '12/30/1899 1:01:16 AM',
  '12/30/1899 1:17:00 AM',
  '12/30/1899 1:

#### Loading a CSV's Data 

In [106]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filepath, d = ','):
    data = np.genfromtxt(filepath, delimiter = d, skip_header = 1, usecols = np.arange(0,23), 
                         invalid_raise = False, names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
bs2017

names = bs2017["Name"]
hits = bs2017["H"]

for i in range(len(names)):
    print(f'{names[i]} had {hits[0]}')
    
new_arr = [bs2017["Name"]]
print(new_arr)

new = np.append(new_arr, [hits], axis = 0)
new

b'Christian Vazquez' had 94
b'Mitch Moreland' had 94
b'Dustin Pedroia' had 94
b'Xander Bogaerts' had 94
b'Rafael Devers' had 94
b'Andrew Benintendi' had 94
b'Jackie Bradley Jr.' had 94
b'Mookie Betts' had 94
b'Hanley Ramirez' had 94
b'Sandy Leon' had 94
b'Chris Young' had 94
b'Deven Marrero' had 94
b'Eduardo Nunez' had 94
b'Brock Holt' had 94
b'Josh Rutledge' had 94
b'Pablo Sandoval' had 94
b'Sam Travis' had 94
b'Tzu-Wei Lin' had 94
b'Marco Hernandez' had 94
b'Rajai Davis' had 94
b'Steve Selsky' had 94
b'Blake Swihart' had 94
b"Chase d'Arnaud" had 94
[array([b'Christian Vazquez', b'Mitch Moreland', b'Dustin Pedroia',
       b'Xander Bogaerts', b'Rafael Devers', b'Andrew Benintendi',
       b'Jackie Bradley Jr.', b'Mookie Betts', b'Hanley Ramirez',
       b'Sandy Leon', b'Chris Young', b'Deven Marrero', b'Eduardo Nunez',
       b'Brock Holt', b'Josh Rutledge', b'Pablo Sandoval', b'Sam Travis',
       b'Tzu-Wei Lin', b'Marco Hernandez', b'Rajai Davis',
       b'Steve Selsky', b'Blake Swi

array([[b'Christian Vazquez', b'Mitch Moreland', b'Dustin Pedroia',
        b'Xander Bogaerts', b'Rafael Devers', b'Andrew Benintendi',
        b'Jackie Bradley Jr.', b'Mookie Betts', b'Hanley Ramirez',
        b'Sandy Leon', b'Chris Young', b'Deven Marrero',
        b'Eduardo Nunez', b'Brock Holt', b'Josh Rutledge',
        b'Pablo Sandoval', b'Sam Travis', b'Tzu-Wei Lin',
        b'Marco Hernandez', b'Rajai Davis', b'Steve Selsky',
        b'Blake Swihart', b"Chase d'Arnaud"],
       [b'94', b'125', b'119', b'156', b'63', b'155', b'118', b'166',
        b'120', b'61', b'57', b'36', b'53', b'28', b'24', b'21', b'20',
        b'15', b'16', b'9', b'1', b'1', b'1']], dtype='|S25')

#### Summing the top 5 hitters for HR's

In [110]:
# find the top 5 homerun hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
home_runs = bs2017["HR"]

# Step 2
player_names = bs2017["Name"]

# Step 3
new_names = []

# Step 4
for name in player_names:
    new_names.append(name.decode('utf-8'))
# print(new_names)

# Step 5
zipped_values = []
for i in range(len(new_names)):
    zipped_values.append((new_names[i], home_runs[i]))
print(zipped_values)

# zipped_values = list(zip(new_names,home_runs))
# print(zipped_values)

# Step 6 - get top five
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse = True)
sorted_hr[0:6]

[('Christian Vazquez', 5), ('Mitch Moreland', 22), ('Dustin Pedroia', 7), ('Xander Bogaerts', 10), ('Rafael Devers', 10), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17), ('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Sandy Leon', 7), ('Chris Young', 7), ('Deven Marrero', 4), ('Eduardo Nunez', 8), ('Brock Holt', 0), ('Josh Rutledge', 0), ('Pablo Sandoval', 4), ('Sam Travis', 0), ('Tzu-Wei Lin', 0), ('Marco Hernandez', 0), ('Rajai Davis', 0), ('Steve Selsky', 0), ('Blake Swihart', 0), ("Chase d'Arnaud", 0)]


[('Mookie Betts', 24),
 ('Hanley Ramirez', 23),
 ('Mitch Moreland', 22),
 ('Andrew Benintendi', 20),
 ('Jackie Bradley Jr.', 17),
 ('Xander Bogaerts', 10)]

# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
# formula = weight / (height**2) * 730

height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

formula = weight / (height**2) * 730
print(formula)



# def bmi(h_1, w_1):
#     calc_bmi = []
#     for i in range(len(h_1)):
#         calc_bmi.append((w_1 /(h_1**2) * 730))
#     return calc_bmi
# print(bmi((height, weight))


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [3]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def makeMatrix(low,high,shape,data_type = float):
    #use np.arange function #np.arange makes list for us which creates the range (0,9)
    M_1 = np.arange(low, high, 1, data_type)
    # ((3,3)) - shape
    M_2 = M_1.reshape(shape)
    print(M_2)

makeMatrix(0,9,(3,3), int)
    
    

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [4]:
import csv
import numpy as np

#Test to make sure you have the correct data

def open_csv(filepath, d = ','):
    data = []
    with open(filepath, encoding = 'utf-8') as myData:
        info = csv.reader(myData, delimiter = d)
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('../files/redsox_2017_hitting.txt')
csv_data = open_csv('../files/redsox_2018_hitting.txt')

In [6]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filepath, d = ','):
    data = np.genfromtxt(filepath, delimiter = d, skip_header = 1, usecols = np.arange(0,23), 
                         invalid_raise = False, names = FIELDS, dtype = DATATYPES)
    return data

rs2017 = load_data('../files/redsox_2017_hitting.txt')
rs2018 = load_data('../files/redsox_2018_hitting.txt')
rs2017
rs2018

slg_1 = rs2017['SLG']
slg_2 = rs2018['SLG']

total_slg2017 = np.array(rs2017["SLG"]).shape

total_slg2018 = np.array(rs2018["SLG"]).shape

if total_slg2017 > total_slg2018:
    print ("Year 2017 was a better year based on SLG")
else:
    print ("Year 2018 was a better year based on SLG")
    
    

Year 2017 was a better year based on SLG
